### ISSUE TITLE
OrthoANI value not maximal

### ISSUE THREAD

**Issue by Lcornet** [althonos/orthoani#2]
When I run orthoANI on a genome against itself, I don't have the maximal value:

orthoani -q GCA_019285895.1.fna -r GCA_019285895.1.fna, the value is 0.9941807049214084.

Did I made something wrong ?

**Comment by althonos** [comment]
Hi, I was not extracting the BLAST results properly which would cause some duplicate results to be processed for very high similarity genomes. This should be fixed now in `v0.6.0`, an a self VS self gives 100% ANI.
